name: Veracode SCA

on:
  workflow_call:
  
jobs:
  veracode_sca:
    runs-on: ["linux"]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup
        run: |
          mkdir .srcclr
          mkdir srcclr
          pwd
      
      - name: Create Agent.yml
        working-directory: .srcclr
        run: |
          echo -e "agentAuthorization: ${{ secrets.scatoken }}\nscmType: GIT > agent.yml"
          ls -la          
          
      - name: Setup Srcclr
        working-directory: srcclr
        run: |
          curl -O https://download.sourceclear.com/srcclr-3.8.34-linux.tgz
          tar -zxvf srcclr-3.8.34-linux.tgz
          ls -la
          
      - name: Test
        working-directory: srcclr
        run: |
          ls -la
          ./srcclr scan --url https://github.com/WebGoat/WebGoat.git
          
          
      
      
